app:
  image: vazina/colt-camp:latest
  ports:
    - 3000:3000
  environment:
    - IP=0.0.0.0
  volumes:
    - .:/opt/ColtCamp/app
  links:
    - db

db:
    image: mongo:3.4.6
    ports:
        - 27017
